# Generated by Django 3.2.5 on 2021-08-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210805_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='biograpy',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='contacts',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
